name: Mac M1

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Install ffmpeg
        run: brew install ffmpeg
      - name: Build
        run: cargo build --verbose
      - name: Check without default features
        run: cargo check --no-default-features
      - name: Run tests
        run: cargo test --all-targets --all-features --examples --verbose